#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build a disk image whose root filesystem is inside an LVM2 volume group.

Every other fixture in this repository is produced by the tool that owns the
format - mkfs, qemu-img, ewfacquire - because a fixture written by the same
project that reads it only proves the reader agrees with itself. This one is
the exception, and the reason is worth stating plainly: pvcreate, vgcreate and
lvcreate all go through device-mapper, which needs root, and the fixtures have
to be buildable by anyone reviewing this without handing them a root shell.

So the LVM2 metadata here is written from the on-disk format instead. What
that buys is still real: a disk where the partition table stops at a physical
volume, and the filesystem is only reachable by parsing LVM metadata and
mapping logical extents onto physical ones. That is the shape of nearly every
RHEL and Ubuntu server install, and a reader that skips the volume layer finds
a partition of type 8e, no filesystem, and reports an empty disk.

    python3 tools/mklvm.py tests/fixtures/ext4.img tests/fixtures/lvm-ext4.dd

The linear layout below is what LVM produces for a default install. A striped
or mirrored volume group cannot be built here honestly - the mapping would be
written by the same arithmetic that reads it - so those paths are implemented
against the format and not covered by this fixture.
"""

import os
import struct
import sys

SECTOR = 512
MB = 1024 * 1024

LABEL_SECTOR = 1                 # where LVM writes its label, by default
MDA_OFFSET = 4096                # the metadata area, right after the label
MDA_SIZE = 1044480               # 1 MiB less the 4 KiB in front of it
PE_START = 2048                  # first physical extent, at 1 MiB
EXTENT_SECTORS = 8192            # 4 MiB extents, the LVM default
PART_OFFSET = 1 * MB             # where the partition starts on the disk

PV_UUID = "lNsGHT0000pv0000AAAABBBBCCCCDDDD"
VG_UUID = "lNsGHT0000vg0000AAAABBBBCCCCDDDD"
LV_UUID = "lNsGHT0000lv0000AAAABBBBCCCCDDDD"

MDA_MAGIC = b" LVM2 x[5A%r0N*>"

METADATA = """\
vg_linsight {
id = "%s"
seqno = 1
format = "lvm2"
status = ["RESIZEABLE", "READ", "WRITE"]
flags = []
extent_size = %d
max_lv = 0
max_pv = 0
metadata_copies = 0

physical_volumes {

pv0 {
id = "%s"
device = "/dev/sda1"
status = ["ALLOCATABLE"]
flags = []
dev_size = %d
pe_start = %d
pe_count = %d
}
}

logical_volumes {

root {
id = "%s"
status = ["READ", "WRITE", "VISIBLE"]
flags = []
creation_time = 1774390000
creation_host = "web01"
segment_count = 1

segment1 {
start_extent = 0
extent_count = %d
type = "striped"
stripe_count = 1
stripes = [
"pv0", 0
]
}
}
}
}
# Generated by tools/mklvm.py
contents = "Text Format Volume Group"
version = 1
description = ""
"""


def dashed(uuid32):
    """LVM writes a PV uuid grouped 6-4-4-4-4-4-6 in its text metadata."""
    parts = (uuid32[0:6], uuid32[6:10], uuid32[10:14], uuid32[14:18],
             uuid32[18:22], uuid32[22:26], uuid32[26:32])
    return "-".join(parts)


def build(fs_path, out_path):
    fs_size = os.path.getsize(fs_path)
    data_bytes = PE_START * SECTOR
    extent_bytes = EXTENT_SECTORS * SECTOR
    extents = (fs_size + extent_bytes - 1) // extent_bytes
    pv_bytes = data_bytes + extents * extent_bytes
    disk_bytes = PART_OFFSET + pv_bytes

    text = METADATA % (dashed(VG_UUID), EXTENT_SECTORS, dashed(PV_UUID),
                       pv_bytes // SECTOR, PE_START, extents,
                       dashed(LV_UUID), extents)
    blob = text.encode("ascii")

    with open(out_path, "wb") as out:
        out.truncate(disk_bytes)

        # -- MBR: one partition of type 8e, Linux LVM ----------------------
        mbr = bytearray(SECTOR)
        entry = bytearray(16)
        entry[0] = 0x00                                   # not bootable
        entry[4] = 0x8E                                   # Linux LVM
        struct.pack_into("<I", entry, 8, PART_OFFSET // SECTOR)
        struct.pack_into("<I", entry, 12, pv_bytes // SECTOR)
        mbr[446:462] = entry
        mbr[510:512] = b"\x55\xAA"
        out.seek(0)
        out.write(mbr)

        # -- the PV label, and the pv_header inside it ---------------------
        # label_header: LABELONE, the sector it sits in, a crc, where the
        # contents start, and the type. The crc is left zero: nothing that
        # reads this verifies it, and a wrong one would be worse than none.
        label = bytearray(SECTOR)
        label[0:8] = b"LABELONE"
        struct.pack_into("<Q", label, 8, LABEL_SECTOR)
        struct.pack_into("<I", label, 16, 0)              # crc
        struct.pack_into("<I", label, 20, 32)             # contents at +32
        label[24:32] = b"LVM2 001"

        body = bytearray(SECTOR - 32)
        body[0:32] = PV_UUID.encode("ascii")
        struct.pack_into("<Q", body, 32, pv_bytes)
        # data areas: one, starting at pe_start and running to the end
        struct.pack_into("<QQ", body, 40, data_bytes, 0)
        struct.pack_into("<QQ", body, 56, 0, 0)           # terminator
        # metadata areas: one, the mda below
        struct.pack_into("<QQ", body, 72, MDA_OFFSET, MDA_SIZE)
        struct.pack_into("<QQ", body, 88, 0, 0)           # terminator
        label[32:SECTOR] = body[:SECTOR - 32]
        out.seek(PART_OFFSET + LABEL_SECTOR * SECTOR)
        out.write(label)

        # -- the metadata area ---------------------------------------------
        mda = bytearray(SECTOR)
        struct.pack_into("<I", mda, 0, 0)                 # checksum
        mda[4:20] = MDA_MAGIC
        struct.pack_into("<I", mda, 20, 1)                # version
        struct.pack_into("<Q", mda, 24, MDA_OFFSET)       # this area's start
        struct.pack_into("<Q", mda, 32, MDA_SIZE)
        # one raw_locn: the current metadata text, right after this header
        struct.pack_into("<QQII", mda, 40, SECTOR, len(blob), 0, 0)
        struct.pack_into("<QQII", mda, 64, 0, 0, 0, 0)    # terminator
        out.seek(PART_OFFSET + MDA_OFFSET)
        out.write(mda)
        out.write(blob)

        # -- the logical volume's extents, which are the filesystem --------
        out.seek(PART_OFFSET + data_bytes)
        with open(fs_path, "rb") as fh:
            while True:
                chunk = fh.read(4 * MB)
                if not chunk:
                    break
                out.write(chunk)

    print("[+] %s: MBR -> 8e partition -> vg_linsight -> /dev/vg_linsight/root"
          % out_path)
    print("    %d extents of %d MiB, filesystem at byte %d"
          % (extents, extent_bytes // MB, PART_OFFSET + data_bytes))


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: mklvm.py <filesystem image> <output disk>\n")
        return 2
    build(argv[1], argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
